# Generated by Django 5.0.1 on 2024-03-13 06:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential',
            old_name='binance_api_key',
            new_name='api_key',
        ),
        migrations.RenameField(
            model_name='credential',
            old_name='binance_secret_key',
            new_name='secret_key',
        ),
        migrations.AlterField(
            model_name='credential',
            name='unique_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
