# Generated by Django 5.0.1 on 2024-03-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_rename_binance_api_key_credential_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='platform_type',
            field=models.CharField(choices=[('binance', 'Binance'), ('oanda', 'Oanda'), ('alpace', 'Alpace')], default='binance', max_length=30),
        ),
    ]
