# Generated by Django 5.0.1 on 2024-03-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='symbol',
            field=models.CharField(default='', max_length=30),
        ),
    ]
